package comm;

public enum ConnectionType {
	ADMIN,FULL_UPDATE,KILL_WORKER,KILL_CLIENT,KICK_WORKER,
	
	CLIENT,CLIENT_NEW_PROBLEM,CLIENT_NEW_TASK,CLIENT_CANCEL_ALL_TASKS,START_WORK,CLIENT_NEW_TASK_WAIT,CLIENT_DISCONNECT,
	
	CLASS_SOLVER,CLASS_REQUESTER,APPLET_CLASS_REQUESTER,
	
	MONITOR,
	
	WORKER,JA_WORKER_HELLO,WORKER_FEED, WORKER_RESULTS, PING,PONG,
	WORKER_CANCEL_CLIENT_TASK, WORKER_CANCELED_TASKS, CLEAR_CLIENT,
	FEED_WORKER,WORKER_FEED_IN_PROGRESS,
	WORKER_CANCELED_TASK_OK,WORKER_CANCELED_TASK_NOK, CANCEL_TASK, UPDATE_CLIENT_INFORMATION
}
